Repository Sprint-Part2-Team20/Rolling, pull requests merged in 2024-03, with the labels that each got.

#30 fix/badge-2
  src/components/common/badge/BadgeDesign.module.scss
  src/components/common/badge/EmojiBadge.jsx
Labels: 🗃️component

#29 Feature/modal
  src/components/Modal/Modal.jsx
  src/components/Modal/modal.module.scss
  src/components/common/Profile/Profile.jsx
  src/components/common/Profile/profile.module.scss
  src/components/common/ProfileImage/index.module.scss
Labels: 🗃️component

#38 style : Card컴포넌트 text 3줄요약으로 변경
  src/components/common/Card/card.module.scss
Labels: 🐛fix

#44 Fix/header
  src/components/common/Badge/BadgeDesign.module.scss
  src/components/common/Header/index.jsx
  src/components/common/Header/index.module.scss
  src/components/common/HeaderService/KakaoShareButton.jsx
  src/components/common/HeaderService/headerService.module.scss
Labels: 🗃️component

#42 fix: map함수랜더링 에러 방지
  src/components/CardList/index.jsx
  src/components/common/HeaderService/HeaderService.jsx
  src/components/common/ProfileImages/ProfileImages.jsx
Labels: 🐛fix

#50 Feature/main page
  src/assets/main-article-1.svg
  src/assets/main-article-2.png
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/mainPage.module.scss
  src/utils/imageImport.js
Labels: 📄pages

#49 Feature/list page
  src/App.js
  src/components/CardList/Carousel.jsx
  src/components/CardList/ListOfCard.jsx
  src/components/CardList/ListOfCard.module.scss
  src/components/CardList/carousel.module.scss
  src/components/CardList/data.jsx
  src/components/CardList/index.jsx
  src/components/CardList/index.module.scss
  src/components/Option/index.jsx
  src/constants/fetchUrl.js
  src/pages/CardCreatePage/CardCreatePage.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/listPage.module.scss
Labels: 📄pages

#43 Feature/postpage
  package-lock.json
  package.json
  src/assets/closeIcon.svg
  src/assets/completedIcon.svg
  src/assets/plusLogo.svg
  src/assets/rollingIcon.png
  src/assets/trashcanIcon.svg
  src/components/Modal/Modal.jsx
  src/components/common/Badge/BadgeDesign.module.scss
  src/components/common/Card/Card.jsx
  src/components/common/Card/DeleteButton.jsx
  src/components/common/Card/card.module.scss
  src/components/common/Card/deleteButton.module.scss
  src/components/common/HeaderService/HeaderService.jsx
  src/components/common/HeaderService/headerService.module.scss
  src/constants/fetchUrl.js
  src/constants/mode.js
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/components/PostCard.jsx
  src/pages/PostPage/components/Toast.jsx
  src/pages/PostPage/components/postCard.module.scss
  src/pages/PostPage/components/toast.module.scss
  src/pages/PostPage/postPage.module.scss
  src/utils/imageImport.js
Labels: 📄pages

#48 feat: CardCreatePage 추가
  .eslintrc
  src/components/Option/index.jsx
  src/components/Option/index.module.scss
  src/pages/CardCreatePage/CardCreatePage.jsx
  src/pages/CardCreatePage/cardCreatePage.module.scss
Labels: 📄pages

#52 fix-pages
  src/components/CardList/carousel.module.scss
  src/components/CardList/listOfCard.module.scss
  src/pages/MainPage/mainPage.module.scss
Labels: 🐛fix

#55 Fix/postpage
  src/App.js
  src/components/common/Card/Card.jsx
  src/components/common/Card/card.module.scss
  src/constants/fetchUrl.js
  src/pages/CardCreatePage/CardCreatePage.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/components/postCard.module.scss
  src/pages/PostPage/components/toast.module.scss
  src/pages/PostPage/postPage.module.scss
  src/utils/setPostPageBackground.js
Labels: 🐛fix

#59 fix: 메시지 삭제후 저장완료 클릭시 HeaderService의 작성인원 랜더링
  src/pages/PostPage/PostPage.jsx
Labels: 🐛fix

#60 Feature/textfield
  src/assets/arrow_top.svg
  src/components/Textfield/index.jsx
  src/components/Textfield/index.module.scss
  src/utils/imageImport.js
Labels: 🗃️component

#61 Feature/loading
  src/App.js
  src/assets/loadingSpinner.gif
  src/components/common/Loading/Loading.jsx
  src/components/common/Loading/loading.module.scss
  src/index.js
Labels: 🤔continue

#66 feature/button2
  package-lock.json
  package.json
  src/assets/deleted-black.svg
  src/assets/deleted-white.svg
  src/assets/plus.svg
  src/assets/smile-white.svg
  src/assets/smile.svg
  src/components/common/Button/Button.jsx
  src/components/common/Button/button.module.scss
  src/utils/imageImport.js
Labels: 🗃️component

#68 Fix/listpage
  src/components/CardList/CardSkeleton.jsx
  src/components/CardList/Carousel.jsx
  src/components/CardList/cardSkeleton.module.scss
Labels: 🗃️component, 🐛fix

#72 fix: Card button
  src/components/common/Card/Card.jsx
Labels: 🐛fix

#74 fix: 삭제가 완료되야 리스트로 넘어가도록 수정
  src/components/Modal/MessageClearModal.jsx
  src/pages/ListPage/ListPage.jsx
Labels: 🐛fix

#73 Fix/MessageCreatePage
  src/components/FileInput/FileInput.jsx
  src/components/FileInput/fileInput.module.scss
  src/components/Modal/modal.module.scss
  src/components/common/Card/Card.jsx
  src/components/common/Card/card.module.scss
  src/pages/CardCreatePage/CardCreatePage.jsx
  src/pages/CardCreatePage/cardCreatePage.module.scss
  src/pages/MessageCreatePage/MessageCreatePage.jsx
  src/pages/MessageCreatePage/messageCreatePage.module.scss
Labels: 🗃️component, 🐛fix

#79 Fix/deploy-error
  .eslintrc
  package-lock.json
  package.json
Labels: 🐛fix

#82 fix: 모바일 버전 모달 크기조정
  src/components/Modal/messageClearModal.module.scss
  src/components/Modal/modal.module.scss
Labels: 🐛fix

#84 style: 모바일 모달 스타일 에러 수정
  src/components/Modal/messageClearModal.module.scss
  src/components/Modal/modal.module.scss
  src/components/common/Profile/profile.module.scss
Labels: 🐛fix
